# Fabric Configuration
server:
  address: ":8080"
  
proxy:
  enabled: true
  port: 8081
  
database:
  host: "localhost"
  port: 5432
  name: "fabric"
  user: "fabric"
  password: "fabric"
  
nats:
  url: "nats://localhost:4222"
  
tailscale:
  authkey: ""
  hostname: "fabric-node"
  
containerd:
  socket: "/run/containerd/containerd.sock"
  namespace: "fabric"
  
metering:
  endpoint: "http://localhost:8082"
  
storage:
  iroh:
    node_path: "/tmp/iroh"
