apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: station-ingress
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`station.codecflow.ai`)
      kind: Rule
      services:
        - name: target-service
          port: 8080
  tls:
    certResolver: letsencrypt
