name: CI & Docker

on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint (all modules)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.3

      - name: Sync workspace
        run: go work sync

      - name: go fmt
        run: go fmt ./...

      - name: go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.0
          args: --timeout 5m

  test:
    name: Test ${{ matrix.app }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [shuttle, weaver]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.3

      - name: Sync workspace
        run: go work sync

      - name: Run tests for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: |
          go test ./... -v -coverprofile=coverage.out

      - name: Upload coverage ({{ matrix.app }})
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.app }}
          path: ${{ matrix.app }}/coverage.out

  build-and-push:
    name: Build & Push Docker images
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        image:
          - name: cf-shuttle
            dockerfile: build/shuttle/Dockerfile
          - name: cf-weaver
            dockerfile: build/weaver/Dockerfile
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ matrix.image.name }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:latest
