name: Fabric CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  lint_commit:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: npm install -g @commitlint/cli @commitlint/config-conventional commitlint-plugin-regex-match
      - name: Lint Message
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Use PR title for PRs
            MESSAGE="${{ github.event.pull_request.title }}"
          else
            # Use commit subject for direct pushes
            MESSAGE=$(git log -1 --pretty=%s)
          fi
          echo "$MESSAGE" | npx commitlint

  lint_code:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Cache Go modules & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.work.sum','**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Sync workspace
        run: go work sync
      - name: go fmt
        run: |
          ( cd shuttle && go fmt ./... )
          ( cd weaver && go fmt ./... )
      - name: go vet
        env:
          GOFLAGS: -mod=readonly
        run: go vet ./shuttle/... ./weaver/...
      - name: go mod tidy check
        run: |
          ( cd shuttle && go mod tidy )
          ( cd weaver  && go mod tidy )
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: ./shuttle/... ./weaver/... --timeout 5m

  test_unit:
    name: Test ${{ matrix.app }}
    needs: lint_code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [shuttle, weaver]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      - name: Cache Go modules & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Sync workspace
        run: go work sync
      - name: Run tests for ${{ matrix.app }}
        working-directory: ${{ matrix.app }}
        run: go test ./... -v -coverprofile=coverage.out
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.app }}
          path: coverage.out

  build_and_push:
    name: Build & Push ${{ matrix.app }}
    needs: test_unit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        include:
          - app: shuttle
            docker_name: cf-shuttle
          - app: weaver
            docker_name: cf-weaver

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          if [ -n "$PR_NUMBER" ]; then
            echo "IMAGE_TAG=pr-$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          fi
          echo "PUSH=true" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.app }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/${{ matrix.app }}/Dockerfile
          push: ${{ steps.tag.outputs.PUSH }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.docker_name }}:${{ steps.tag.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Publish Release & Retag Images
    needs: build_and_push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_TOKEN }}

      - name: Install semantic-release & plugins
        run: |
          npm install -g semantic-release@20 @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/github @semantic-release/exec @semantic-release/git

      - name: Run semantic-release
        id: sr
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release

      - name: Retag & Push Images with v${{ steps.sr.outputs.nextRelease_version }}
        run: |
          VERSION=v${{ steps.sr.outputs.nextRelease_version }}
          for app in shuttle weaver; do
            name=cf-$app
            # pull the latest image we pushed in build_and_push
            docker pull ghcr.io/${{ github.repository_owner }}/$name:latest

            # tag it with the new semver and as latest
            docker tag ghcr.io/${{ github.repository_owner }}/$name:latest \
                       ghcr.io/${{ github.repository_owner }}/$name:$VERSION

            # push both
            docker push ghcr.io/${{ github.repository_owner }}/$name:$VERSION
            docker push ghcr.io/${{ github.repository_owner }}/$name:latest
          done
